module.exports = {
    titles: [`A szeretet mindenkié`],
    sections: [
`A szeretet mindenkié,
a szeretet mindenkié,
csak meg kell keresni a forrását,
a szeretet mindenkié.
` ,`Az öröm mindenkié...
` ,`A béke mindenkié...
` ,`A türelem mindenkié...
` ,`A kedvesség mindenkié...
` ,`A jóság mindenkié...
` ,`A hűség mindenkié...
` ,`A szelídség mindenkié...
` ,`A tisztaság mindenkié...
` ,`A boldogság mindenkié...
` ,`A hála mindenkié...
` ,`Az erő mindenkié...
` ,`Jézus mindenkié, Jézus mindenkié,
csak meg kell fogni a két kezét, mert Jézus mindenkié!
` 
    ]
}
