module.exports = {
    titles: [`Alleluja, alleluja`,`Jézus szeret`],
    sections: [
`Alleluja, alleluja, alleluja, alleluja!
Alleluja, alleluja, alleluja, alleluja!
` ,`Jézus szeret...
Eljön újra...
Marana tha...
Alleluja...
` 
    ]
}
