module.exports = {
    titles: [`Az élő Jézust magasztalom`],
    sections: [
`// Az élő Jézust magasztalom,
és kiárad rám a Lélek. //
// Őt magasztalom, Őt magasztalom,
és kiárad rám a Lélek. //
` ,`Egy új nyelven imádom Őt,
ha kiárad rám a Lélek...
És imádom Őt, és imádom Őt,
ha kiárad rám a Lélek...
` ,`És Jézustól erőt kapok,
ha kiárad rám a Lélek...
Új erőt kapok, új erőt kapok,
ha kiárad rám a Lélek...
` ,`Nem várok már, új harcba megyek,
ha kiárad rám a Lélek...
Új harcba megyek, új harcba megyek,
ha kiárad rám a Lélek...
` ,`És Jézus nevében csatát nyerek,
ha kiárad rám a Lélek...
És csatát nyerek, és csatát nyerek
ha kiárad rám a Lélek...
` ,`Ő betölti lelkem és dicsérem Őt,
ha kiárad rám a Lélek...
És dicsérem Őt, dicsérem Őt,
ha kiárad rám a Lélek...
` 
    ]
}
