module.exports = {
    titles: [`Az Úrnak szüksége van rád`],
    sections: [
`Az Úrnak szüksége van rád,
oly nagyon szüksége van rád.
` ,`Fontosabb vagy te, mint az égbolt,
fontosabb vagy te, mint a föld,
fontosabb vagy te, mint a tenger,
nagyon fontos vagy te!
` ,`Az Úrnak szüksége van rám...
Fontosabb vagyok mint...
` ,`Nekünk szükségünk van Rád (Atyám)...
Fontosabb vagy Te mint...
` ,`Nekem szükségem van rád (testvérem)...
Fontosabb vagy te...
` ,`Neked szükséged van rám...
Fontosabb vagyok...
` 
    ]
}
