module.exports = {
    titles: [`Gloria, gloria`],
    sections: [
`Gloria, gloria!...
Gloria hosanna, hosanna, hosanna!...
Alleluja Jézusnak, alleluja!...
Sanctus Dominus Deus Sabaoth!...
` 
    ]
}
