module.exports = {
    titles: [`Kadosh`],
    sections: [
`Kadosh, kadosh, kadosh,...
Adonai, Elohim, tz'va'ot,...
Asher hayah v'hoveh v'yavo.
` ,`Szent az Úr, dicsérem, mert szent az Úr,...
Adonai, élő Úr, seregek Istene,...
Aki volt, Aki van s Aki eljövendő!
` 
    ]
}
