module.exports = {
    titles: [`Ó, szívemben itt a menny`],
    sections: [
`Ó, szívemben itt a menny!
` ,`Az Isten országa van itt, szívemben itt a menny!
Ő Úr az én életemben, szívemben...
és nagy öröm van bensőmben,...
szent, tiszta fénnyel átölel,...
` ,`Trónjának temploma vagyunk,...
kősziklánkká lett Jézusunk,...
Ő visszajön, hogy elvigyen,...
Szentlélekkel mondjuk: Jöjj el!...
` 
    ]
}
