module.exports = {
    titles: [`Olyan hitet`],
    sections: [
`Olyan hitet, mint a szikla, olyan hitet, mint a szikla,
olyan hitet kaptam Tőled lelkembe.
Olyan hitet, mint a szikla, olyan hitet, mint a szikla,
olyan hitet kaptam Tőled lelkembe.
` ,`Olyan reményt, mint a tavasz...
` ,`Olyan szeretetet, mint a tenger,...
` ,`Olyan békét, mint a folyó...
` ,`Olyan örömöt, mint a forrás...
` ,`Olyan szomjat, mint a szarvas...
` ,`Olyan derűt, mint a napfény...
` 
    ]
}
